apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/kubernetes-sigs/agent-sandbox/k8s?ref=main

images:
- name: ko://sigs.k8s.io/agent-sandbox/cmd/agent-sandbox-controller
  newName: us-central1-docker.pkg.dev/k8s-staging-images/agent-sandbox/agent-sandbox-controller
  newTag: latest-main