apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- provider-kubernetes.yaml
- provider-kubernetes-config.yaml
- provider-kubernetes-rbac.yaml
- network-policies/platform-egress.yaml
- ghcr-token-refresher/cronjob.yaml
