apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ksops
  annotations:
    argocd.argoproj.io/sync-wave: "0"

resources:
  - cmp-plugin.yaml
  - age-key-guardian.yaml

patches:
  - path: patches/repo-server-ksops-sidecar.yaml
    target:
      kind: Deployment
      name: argocd-repo-server
      namespace: argocd
